apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
  namespace: nestjs
  labels:
    app: nestjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: nestjs
        image: nestjs
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      restartPolicy: Always
